services:
  #
  # Postgres
  #
  postgres:
    image: postgres:17.2-alpine
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command:
      - "postgres"
      - -c
      - wal_level=minimal # write even less to disk to speed up unit tests
      - -c
      - max_wal_senders=0 # write even less to disk to speed up unit tests
    tmpfs:
      - /var/lib/postgresql/data:rw # speeds up writing for testing
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-p", "5432"]
      interval: 1s
      timeout: 5s
      retries: 10

  #
  # Temporal
  #
  temporal:
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=postgres
      - POSTGRES_SEEDS=postgres
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/auto-setup:1.28.1
    ports:
      - 7244:7233
    volumes:
      - ./magefiles/temporal:/etc/temporal/config/dynamicconfig
    healthcheck:
      test: ["CMD", "temporal", "operator", "cluster", "health"]
      interval: 2s
      timeout: 5s
      retries: 60
      start_period: 10s
  temporal-ui:
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:8080
      - TEMPORAL_CSRF_COOKIE_INSECURE=true
    image: temporalio/ui:2.34.0
    ports:
      - 7979:8080