// Code generated by mockery v2.51.1. DO NOT EDIT.

package stdlambdamock

import (
	context "context"

	lambda "github.com/aws/aws-sdk-go-v2/service/lambda"
	mock "github.com/stretchr/testify/mock"
)

// MockLambda is an autogenerated mock type for the Lambda type
type MockLambda struct {
	mock.Mock
}

type MockLambda_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLambda) EXPECT() *MockLambda_Expecter {
	return &MockLambda_Expecter{mock: &_m.Mock}
}

// Invoke provides a mock function with given fields: ctx, params, optFns
func (_m *MockLambda) Invoke(ctx context.Context, params *lambda.InvokeInput, optFns ...func(*lambda.Options)) (*lambda.InvokeOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Invoke")
	}

	var r0 *lambda.InvokeOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *lambda.InvokeInput, ...func(*lambda.Options)) (*lambda.InvokeOutput, error)); ok {
		return rf(ctx, params, optFns...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *lambda.InvokeInput, ...func(*lambda.Options)) *lambda.InvokeOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lambda.InvokeOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *lambda.InvokeInput, ...func(*lambda.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLambda_Invoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invoke'
type MockLambda_Invoke_Call struct {
	*mock.Call
}

// Invoke is a helper method to define mock.On call
//   - ctx context.Context
//   - params *lambda.InvokeInput
//   - optFns ...func(*lambda.Options)
func (_e *MockLambda_Expecter) Invoke(ctx interface{}, params interface{}, optFns ...interface{}) *MockLambda_Invoke_Call {
	return &MockLambda_Invoke_Call{Call: _e.mock.On("Invoke",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockLambda_Invoke_Call) Run(run func(ctx context.Context, params *lambda.InvokeInput, optFns ...func(*lambda.Options))) *MockLambda_Invoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*lambda.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*lambda.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*lambda.InvokeInput), variadicArgs...)
	})
	return _c
}

func (_c *MockLambda_Invoke_Call) Return(_a0 *lambda.InvokeOutput, _a1 error) *MockLambda_Invoke_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLambda_Invoke_Call) RunAndReturn(run func(context.Context, *lambda.InvokeInput, ...func(*lambda.Options)) (*lambda.InvokeOutput, error)) *MockLambda_Invoke_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLambda creates a new instance of MockLambda. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLambda(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLambda {
	mock := &MockLambda{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
