// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: fx/stdtemporalfx/internal/v1/work.proto

package internalv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/cludden/protoc-gen-go-temporal/gen/temporal/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FooInput struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Bar         *string                `protobuf:"bytes,1,opt,name=bar"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FooInput) Reset() {
	*x = FooInput{}
	mi := &file_fx_stdtemporalfx_internal_v1_work_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FooInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FooInput) ProtoMessage() {}

func (x *FooInput) ProtoReflect() protoreflect.Message {
	mi := &file_fx_stdtemporalfx_internal_v1_work_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FooInput) GetBar() string {
	if x != nil {
		if x.xxx_hidden_Bar != nil {
			return *x.xxx_hidden_Bar
		}
		return ""
	}
	return ""
}

func (x *FooInput) SetBar(v string) {
	x.xxx_hidden_Bar = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *FooInput) HasBar() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *FooInput) ClearBar() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Bar = nil
}

type FooInput_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Bar *string
}

func (b0 FooInput_builder) Build() *FooInput {
	m0 := &FooInput{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Bar != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Bar = b.Bar
	}
	return m0
}

type FooOutput struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FooOutput) Reset() {
	*x = FooOutput{}
	mi := &file_fx_stdtemporalfx_internal_v1_work_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FooOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FooOutput) ProtoMessage() {}

func (x *FooOutput) ProtoReflect() protoreflect.Message {
	mi := &file_fx_stdtemporalfx_internal_v1_work_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type FooOutput_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 FooOutput_builder) Build() *FooOutput {
	m0 := &FooOutput{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_fx_stdtemporalfx_internal_v1_work_proto protoreflect.FileDescriptor

const file_fx_stdtemporalfx_internal_v1_work_proto_rawDesc = "" +
	"\n" +
	"'fx/stdtemporalfx/internal/v1/work.proto\x12\x1cfx.stdtemporalfx.internal.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1atemporal/v1/temporal.proto\"$\n" +
	"\bFooInput\x12\x18\n" +
	"\x03bar\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03bar\"\v\n" +
	"\tFooOutput2z\n" +
	"\vTestService\x12\\\n" +
	"\x03Foo\x12&.fx.stdtemporalfx.internal.v1.FooInput\x1a'.fx.stdtemporalfx.internal.v1.FooOutput\"\x04\x8a\xc4\x03\x00\x1a\r\x8a\xc4\x03\t\n" +
	"\atest-v1B\x80\x02\n" +
	" com.fx.stdtemporalfx.internal.v1B\tWorkProtoP\x01Z>github.com/advdv/stdgo/fx/stdtemporalfx/internal/v1;internalv1\xa2\x02\x03FSI\xaa\x02\x1cFx.Stdtemporalfx.Internal.V1\xca\x02\x1cFx\\Stdtemporalfx\\Internal\\V1\xe2\x02(Fx\\Stdtemporalfx\\Internal\\V1\\GPBMetadata\xea\x02\x1fFx::Stdtemporalfx::Internal::V1b\beditionsp\xe8\a"

var file_fx_stdtemporalfx_internal_v1_work_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fx_stdtemporalfx_internal_v1_work_proto_goTypes = []any{
	(*FooInput)(nil),  // 0: fx.stdtemporalfx.internal.v1.FooInput
	(*FooOutput)(nil), // 1: fx.stdtemporalfx.internal.v1.FooOutput
}
var file_fx_stdtemporalfx_internal_v1_work_proto_depIdxs = []int32{
	0, // 0: fx.stdtemporalfx.internal.v1.TestService.Foo:input_type -> fx.stdtemporalfx.internal.v1.FooInput
	1, // 1: fx.stdtemporalfx.internal.v1.TestService.Foo:output_type -> fx.stdtemporalfx.internal.v1.FooOutput
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fx_stdtemporalfx_internal_v1_work_proto_init() }
func file_fx_stdtemporalfx_internal_v1_work_proto_init() {
	if File_fx_stdtemporalfx_internal_v1_work_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fx_stdtemporalfx_internal_v1_work_proto_rawDesc), len(file_fx_stdtemporalfx_internal_v1_work_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fx_stdtemporalfx_internal_v1_work_proto_goTypes,
		DependencyIndexes: file_fx_stdtemporalfx_internal_v1_work_proto_depIdxs,
		MessageInfos:      file_fx_stdtemporalfx_internal_v1_work_proto_msgTypes,
	}.Build()
	File_fx_stdtemporalfx_internal_v1_work_proto = out.File
	file_fx_stdtemporalfx_internal_v1_work_proto_goTypes = nil
	file_fx_stdtemporalfx_internal_v1_work_proto_depIdxs = nil
}
