// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: fx/stdcrpcauthfx/internal/v1/auth.proto

package internalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WhoAmIRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIRequest) Reset() {
	*x = WhoAmIRequest{}
	mi := &file_fx_stdcrpcauthfx_internal_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIRequest) ProtoMessage() {}

func (x *WhoAmIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fx_stdcrpcauthfx_internal_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type WhoAmIRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 WhoAmIRequest_builder) Build() *WhoAmIRequest {
	m0 := &WhoAmIRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type WhoAmIResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIResponse) Reset() {
	*x = WhoAmIResponse{}
	mi := &file_fx_stdcrpcauthfx_internal_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIResponse) ProtoMessage() {}

func (x *WhoAmIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fx_stdcrpcauthfx_internal_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type WhoAmIResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 WhoAmIResponse_builder) Build() *WhoAmIResponse {
	m0 := &WhoAmIResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var file_fx_stdcrpcauthfx_internal_v1_auth_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50000,
		Name:          "fx.stdcrpcauthfx.internal.v1.required_permission",
		Tag:           "bytes,50000,opt,name=required_permission",
		Filename:      "fx/stdcrpcauthfx/internal/v1/auth.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional string required_permission = 50000;
	E_RequiredPermission = &file_fx_stdcrpcauthfx_internal_v1_auth_proto_extTypes[0]
)

var File_fx_stdcrpcauthfx_internal_v1_auth_proto protoreflect.FileDescriptor

const file_fx_stdcrpcauthfx_internal_v1_auth_proto_rawDesc = "" +
	"\n" +
	"'fx/stdcrpcauthfx/internal/v1/auth.proto\x12\x1cfx.stdcrpcauthfx.internal.v1\x1a google/protobuf/descriptor.proto\"\x0f\n" +
	"\rWhoAmIRequest\"\x10\n" +
	"\x0eWhoAmIResponse2\x81\x01\n" +
	"\rSystemService\x12p\n" +
	"\x06WhoAmI\x12+.fx.stdcrpcauthfx.internal.v1.WhoAmIRequest\x1a,.fx.stdcrpcauthfx.internal.v1.WhoAmIResponse\"\v\x82\xb5\x18\x04read\x90\x02\x01:Q\n" +
	"\x13required_permission\x12\x1e.google.protobuf.MethodOptions\x18І\x03 \x01(\tR\x12requiredPermissionB\x80\x02\n" +
	" com.fx.stdcrpcauthfx.internal.v1B\tAuthProtoP\x01Z>github.com/advdv/stdgo/fx/stdcrpcauthfx/internal/v1;internalv1\xa2\x02\x03FSI\xaa\x02\x1cFx.Stdcrpcauthfx.Internal.V1\xca\x02\x1cFx\\Stdcrpcauthfx\\Internal\\V1\xe2\x02(Fx\\Stdcrpcauthfx\\Internal\\V1\\GPBMetadata\xea\x02\x1fFx::Stdcrpcauthfx::Internal::V1b\beditionsp\xe8\a"

var file_fx_stdcrpcauthfx_internal_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fx_stdcrpcauthfx_internal_v1_auth_proto_goTypes = []any{
	(*WhoAmIRequest)(nil),              // 0: fx.stdcrpcauthfx.internal.v1.WhoAmIRequest
	(*WhoAmIResponse)(nil),             // 1: fx.stdcrpcauthfx.internal.v1.WhoAmIResponse
	(*descriptorpb.MethodOptions)(nil), // 2: google.protobuf.MethodOptions
}
var file_fx_stdcrpcauthfx_internal_v1_auth_proto_depIdxs = []int32{
	2, // 0: fx.stdcrpcauthfx.internal.v1.required_permission:extendee -> google.protobuf.MethodOptions
	0, // 1: fx.stdcrpcauthfx.internal.v1.SystemService.WhoAmI:input_type -> fx.stdcrpcauthfx.internal.v1.WhoAmIRequest
	1, // 2: fx.stdcrpcauthfx.internal.v1.SystemService.WhoAmI:output_type -> fx.stdcrpcauthfx.internal.v1.WhoAmIResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fx_stdcrpcauthfx_internal_v1_auth_proto_init() }
func file_fx_stdcrpcauthfx_internal_v1_auth_proto_init() {
	if File_fx_stdcrpcauthfx_internal_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fx_stdcrpcauthfx_internal_v1_auth_proto_rawDesc), len(file_fx_stdcrpcauthfx_internal_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 1,
			NumServices:   1,
		},
		GoTypes:           file_fx_stdcrpcauthfx_internal_v1_auth_proto_goTypes,
		DependencyIndexes: file_fx_stdcrpcauthfx_internal_v1_auth_proto_depIdxs,
		MessageInfos:      file_fx_stdcrpcauthfx_internal_v1_auth_proto_msgTypes,
		ExtensionInfos:    file_fx_stdcrpcauthfx_internal_v1_auth_proto_extTypes,
	}.Build()
	File_fx_stdcrpcauthfx_internal_v1_auth_proto = out.File
	file_fx_stdcrpcauthfx_internal_v1_auth_proto_goTypes = nil
	file_fx_stdcrpcauthfx_internal_v1_auth_proto_depIdxs = nil
}
