// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: fx/stdpubprivrpcfx/internal/foo/v1/foo.proto

package foov1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitOrganizationRequest) Reset() {
	*x = InitOrganizationRequest{}
	mi := &file_fx_stdpubprivrpcfx_internal_foo_v1_foo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitOrganizationRequest) ProtoMessage() {}

func (x *InitOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fx_stdpubprivrpcfx_internal_foo_v1_foo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type InitOrganizationRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 InitOrganizationRequest_builder) Build() *InitOrganizationRequest {
	m0 := &InitOrganizationRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type InitOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitOrganizationResponse) Reset() {
	*x = InitOrganizationResponse{}
	mi := &file_fx_stdpubprivrpcfx_internal_foo_v1_foo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitOrganizationResponse) ProtoMessage() {}

func (x *InitOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fx_stdpubprivrpcfx_internal_foo_v1_foo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type InitOrganizationResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 InitOrganizationResponse_builder) Build() *InitOrganizationResponse {
	m0 := &InitOrganizationResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type WhoAmIRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Echo        *string                `protobuf:"bytes,1,opt,name=echo"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *WhoAmIRequest) Reset() {
	*x = WhoAmIRequest{}
	mi := &file_fx_stdpubprivrpcfx_internal_foo_v1_foo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIRequest) ProtoMessage() {}

func (x *WhoAmIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fx_stdpubprivrpcfx_internal_foo_v1_foo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WhoAmIRequest) GetEcho() string {
	if x != nil {
		if x.xxx_hidden_Echo != nil {
			return *x.xxx_hidden_Echo
		}
		return ""
	}
	return ""
}

func (x *WhoAmIRequest) SetEcho(v string) {
	x.xxx_hidden_Echo = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *WhoAmIRequest) HasEcho() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *WhoAmIRequest) ClearEcho() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Echo = nil
}

type WhoAmIRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Echo *string
}

func (b0 WhoAmIRequest_builder) Build() *WhoAmIRequest {
	m0 := &WhoAmIRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Echo != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Echo = b.Echo
	}
	return m0
}

type WhoAmIResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Greeting    *string                `protobuf:"bytes,2,opt,name=greeting"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *WhoAmIResponse) Reset() {
	*x = WhoAmIResponse{}
	mi := &file_fx_stdpubprivrpcfx_internal_foo_v1_foo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIResponse) ProtoMessage() {}

func (x *WhoAmIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fx_stdpubprivrpcfx_internal_foo_v1_foo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WhoAmIResponse) GetGreeting() string {
	if x != nil {
		if x.xxx_hidden_Greeting != nil {
			return *x.xxx_hidden_Greeting
		}
		return ""
	}
	return ""
}

func (x *WhoAmIResponse) SetGreeting(v string) {
	x.xxx_hidden_Greeting = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *WhoAmIResponse) HasGreeting() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *WhoAmIResponse) ClearGreeting() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Greeting = nil
}

type WhoAmIResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Greeting *string
}

func (b0 WhoAmIResponse_builder) Build() *WhoAmIResponse {
	m0 := &WhoAmIResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Greeting != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Greeting = b.Greeting
	}
	return m0
}

var File_fx_stdpubprivrpcfx_internal_foo_v1_foo_proto protoreflect.FileDescriptor

const file_fx_stdpubprivrpcfx_internal_foo_v1_foo_proto_rawDesc = "" +
	"\n" +
	",fx/stdpubprivrpcfx/internal/foo/v1/foo.proto\x12\"fx.stdpubprivrpcfx.internal.foo.v1\x1a\x1bbuf/validate/validate.proto\"\x19\n" +
	"\x17InitOrganizationRequest\"\x1a\n" +
	"\x18InitOrganizationResponse\"+\n" +
	"\rWhoAmIRequest\x12\x1a\n" +
	"\x04echo\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04echo\"4\n" +
	"\x0eWhoAmIResponse\x12\"\n" +
	"\bgreeting\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\bgreeting2\x9f\x01\n" +
	"\rSystemService\x12\x8d\x01\n" +
	"\x10InitOrganization\x12;.fx.stdpubprivrpcfx.internal.foo.v1.InitOrganizationRequest\x1a<.fx.stdpubprivrpcfx.internal.foo.v1.InitOrganizationResponse2\x12\n" +
	"\x10ReadWriteService2\x82\x01\n" +
	"\x0fReadOnlyService\x12o\n" +
	"\x06WhoAmI\x121.fx.stdpubprivrpcfx.internal.foo.v1.WhoAmIRequest\x1a2.fx.stdpubprivrpcfx.internal.foo.v1.WhoAmIResponseB\xa0\x02\n" +
	"&com.fx.stdpubprivrpcfx.internal.foo.v1B\bFooProtoP\x01Z?github.com/advdv/stdgo/fx/stdpubprivrpcfx/internal/foo/v1;foov1\xa2\x02\x04FSIF\xaa\x02\"Fx.Stdpubprivrpcfx.Internal.Foo.V1\xca\x02\"Fx\\Stdpubprivrpcfx\\Internal\\Foo\\V1\xe2\x02.Fx\\Stdpubprivrpcfx\\Internal\\Foo\\V1\\GPBMetadata\xea\x02&Fx::Stdpubprivrpcfx::Internal::Foo::V1b\beditionsp\xe8\a"

var file_fx_stdpubprivrpcfx_internal_foo_v1_foo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_fx_stdpubprivrpcfx_internal_foo_v1_foo_proto_goTypes = []any{
	(*InitOrganizationRequest)(nil),  // 0: fx.stdpubprivrpcfx.internal.foo.v1.InitOrganizationRequest
	(*InitOrganizationResponse)(nil), // 1: fx.stdpubprivrpcfx.internal.foo.v1.InitOrganizationResponse
	(*WhoAmIRequest)(nil),            // 2: fx.stdpubprivrpcfx.internal.foo.v1.WhoAmIRequest
	(*WhoAmIResponse)(nil),           // 3: fx.stdpubprivrpcfx.internal.foo.v1.WhoAmIResponse
}
var file_fx_stdpubprivrpcfx_internal_foo_v1_foo_proto_depIdxs = []int32{
	0, // 0: fx.stdpubprivrpcfx.internal.foo.v1.SystemService.InitOrganization:input_type -> fx.stdpubprivrpcfx.internal.foo.v1.InitOrganizationRequest
	2, // 1: fx.stdpubprivrpcfx.internal.foo.v1.ReadOnlyService.WhoAmI:input_type -> fx.stdpubprivrpcfx.internal.foo.v1.WhoAmIRequest
	1, // 2: fx.stdpubprivrpcfx.internal.foo.v1.SystemService.InitOrganization:output_type -> fx.stdpubprivrpcfx.internal.foo.v1.InitOrganizationResponse
	3, // 3: fx.stdpubprivrpcfx.internal.foo.v1.ReadOnlyService.WhoAmI:output_type -> fx.stdpubprivrpcfx.internal.foo.v1.WhoAmIResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fx_stdpubprivrpcfx_internal_foo_v1_foo_proto_init() }
func file_fx_stdpubprivrpcfx_internal_foo_v1_foo_proto_init() {
	if File_fx_stdpubprivrpcfx_internal_foo_v1_foo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fx_stdpubprivrpcfx_internal_foo_v1_foo_proto_rawDesc), len(file_fx_stdpubprivrpcfx_internal_foo_v1_foo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_fx_stdpubprivrpcfx_internal_foo_v1_foo_proto_goTypes,
		DependencyIndexes: file_fx_stdpubprivrpcfx_internal_foo_v1_foo_proto_depIdxs,
		MessageInfos:      file_fx_stdpubprivrpcfx_internal_foo_v1_foo_proto_msgTypes,
	}.Build()
	File_fx_stdpubprivrpcfx_internal_foo_v1_foo_proto = out.File
	file_fx_stdpubprivrpcfx_internal_foo_v1_foo_proto_goTypes = nil
	file_fx_stdpubprivrpcfx_internal_foo_v1_foo_proto_depIdxs = nil
}
