// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: fx/stdriverfx/internal/workheartbeat/v1/work_heartbeat.proto

package workheartbeatv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Args describe possible arguments for the work.
type Args struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_BlockFor *durationpb.Duration   `protobuf:"bytes,1,opt,name=block_for,json=blockFor"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Args) Reset() {
	*x = Args{}
	mi := &file_fx_stdriverfx_internal_workheartbeat_v1_work_heartbeat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Args) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Args) ProtoMessage() {}

func (x *Args) ProtoReflect() protoreflect.Message {
	mi := &file_fx_stdriverfx_internal_workheartbeat_v1_work_heartbeat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Args) GetBlockFor() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_BlockFor
	}
	return nil
}

func (x *Args) SetBlockFor(v *durationpb.Duration) {
	x.xxx_hidden_BlockFor = v
}

func (x *Args) HasBlockFor() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_BlockFor != nil
}

func (x *Args) ClearBlockFor() {
	x.xxx_hidden_BlockFor = nil
}

type Args_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	BlockFor *durationpb.Duration
}

func (b0 Args_builder) Build() *Args {
	m0 := &Args{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_BlockFor = b.BlockFor
	return m0
}

// Output from the work.
type Output struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_BlockTook *durationpb.Duration   `protobuf:"bytes,1,opt,name=block_took,json=blockTook"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_fx_stdriverfx_internal_workheartbeat_v1_work_heartbeat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_fx_stdriverfx_internal_workheartbeat_v1_work_heartbeat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Output) GetBlockTook() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_BlockTook
	}
	return nil
}

func (x *Output) SetBlockTook(v *durationpb.Duration) {
	x.xxx_hidden_BlockTook = v
}

func (x *Output) HasBlockTook() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_BlockTook != nil
}

func (x *Output) ClearBlockTook() {
	x.xxx_hidden_BlockTook = nil
}

type Output_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	BlockTook *durationpb.Duration
}

func (b0 Output_builder) Build() *Output {
	m0 := &Output{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_BlockTook = b.BlockTook
	return m0
}

var File_fx_stdriverfx_internal_workheartbeat_v1_work_heartbeat_proto protoreflect.FileDescriptor

const file_fx_stdriverfx_internal_workheartbeat_v1_work_heartbeat_proto_rawDesc = "" +
	"\n" +
	"<fx/stdriverfx/internal/workheartbeat/v1/work_heartbeat.proto\x12'fx.stdriverfx.internal.workheartbeat.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1egoogle/protobuf/duration.proto\"F\n" +
	"\x04Args\x12>\n" +
	"\tblock_for\x18\x01 \x01(\v2\x19.google.protobuf.DurationB\x06\xbaH\x03\xc8\x01\x01R\bblockFor\"J\n" +
	"\x06Output\x12@\n" +
	"\n" +
	"block_took\x18\x01 \x01(\v2\x19.google.protobuf.DurationB\x06\xbaH\x03\xc8\x01\x01R\tblockTookB\xd2\x02\n" +
	"+com.fx.stdriverfx.internal.workheartbeat.v1B\x12WorkHeartbeatProtoP\x01ZNgithub.com/advdv/stdgo/fx/stdriverfx/internal/workheartbeat/v1;workheartbeatv1\xa2\x02\x04FSIW\xaa\x02'Fx.Stdriverfx.Internal.Workheartbeat.V1\xca\x02'Fx\\Stdriverfx\\Internal\\Workheartbeat\\V1\xe2\x023Fx\\Stdriverfx\\Internal\\Workheartbeat\\V1\\GPBMetadata\xea\x02+Fx::Stdriverfx::Internal::Workheartbeat::V1b\beditionsp\xe8\a"

var file_fx_stdriverfx_internal_workheartbeat_v1_work_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fx_stdriverfx_internal_workheartbeat_v1_work_heartbeat_proto_goTypes = []any{
	(*Args)(nil),                // 0: fx.stdriverfx.internal.workheartbeat.v1.Args
	(*Output)(nil),              // 1: fx.stdriverfx.internal.workheartbeat.v1.Output
	(*durationpb.Duration)(nil), // 2: google.protobuf.Duration
}
var file_fx_stdriverfx_internal_workheartbeat_v1_work_heartbeat_proto_depIdxs = []int32{
	2, // 0: fx.stdriverfx.internal.workheartbeat.v1.Args.block_for:type_name -> google.protobuf.Duration
	2, // 1: fx.stdriverfx.internal.workheartbeat.v1.Output.block_took:type_name -> google.protobuf.Duration
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_fx_stdriverfx_internal_workheartbeat_v1_work_heartbeat_proto_init() }
func file_fx_stdriverfx_internal_workheartbeat_v1_work_heartbeat_proto_init() {
	if File_fx_stdriverfx_internal_workheartbeat_v1_work_heartbeat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fx_stdriverfx_internal_workheartbeat_v1_work_heartbeat_proto_rawDesc), len(file_fx_stdriverfx_internal_workheartbeat_v1_work_heartbeat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fx_stdriverfx_internal_workheartbeat_v1_work_heartbeat_proto_goTypes,
		DependencyIndexes: file_fx_stdriverfx_internal_workheartbeat_v1_work_heartbeat_proto_depIdxs,
		MessageInfos:      file_fx_stdriverfx_internal_workheartbeat_v1_work_heartbeat_proto_msgTypes,
	}.Build()
	File_fx_stdriverfx_internal_workheartbeat_v1_work_heartbeat_proto = out.File
	file_fx_stdriverfx_internal_workheartbeat_v1_work_heartbeat_proto_goTypes = nil
	file_fx_stdriverfx_internal_workheartbeat_v1_work_heartbeat_proto_depIdxs = nil
}
